In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [5]:
df = pd.read_csv('homeprices2.csv')
df

area  bedroom  age   price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      NaN   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000

In [9]:
#DATA PREPROCESSING

import math
median_bedroom = math.floor(df.bedroom.median())
median_bedroom

3

In [14]:
df.bedroom = df.bedroom.fillna(median_bedroom)

In [16]:
df

area  bedroom  age   price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      3.0   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000

In [19]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedroom','age']],df.price)

LinearRegression()

In [27]:
reg.predict([[3000,3,40]])

array([444400.])

In [49]:
df = pd.read_csv('hiring.csv')
df

experience  test_score  interview_score  salary  Unnamed: 4
0         NaN         8.0                9   50000         NaN
1         NaN         8.0                6   45000         NaN
2         5.0         6.0                7   60000         NaN
3         2.0        10.0               10   65000         NaN
4         7.0         9.0                6   70000         NaN
5         3.0         7.0               10   62000         NaN
6        10.0         NaN                7   72000         NaN
7        11.0         7.0                8   80000         NaN

In [50]:
median_test_score = df.test_score.median()
median_test_score

8.0

In [67]:
df.test_score = df.test_score.fillna(median_test_score)
df.experience = df.experience.apply('five')
df

AttributeError: 'five' is not a valid function for 'Series' object

In [56]:
reg = linear_model.LinearRegression()
reg.fit(df[['experience','test_score','interview_score']],df.salary)

LinearRegression()

In [65]:
reg.predict([[6,10,10]])

array([75124.45414847])

In [60]:
reg.predict([[12,10,10]])

array([92002.18340611])